workflows:
  android-workflow:
    name: Android Build
    environment:
      node: latest
      java: 21
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Generate Icons
        script: |
          npm install @capacitor/assets --save-dev
          npx @capacitor/assets generate
      - name: Fix permissions
        script: chmod +x node_modules/.bin/cap
      - name: Sync Capacitor
        script: npx cap sync
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
